### PR TITLE
fix: corrects UI and Mobile view

### PR DESCRIPTION
**Pull request by RamanaRaj7**
fix for issue #2 and #3

### CODE REVIEW

**Comment by RamanaRaj7** [comment]
hint url is moved up because the text field was not completely visible in Mobile view

**Comment by mattrltrent** [comment]
Again, good stuff @RamanaRaj7!

Screenshot 2024-06-06 at 12 02 23 PM

If possible, could you ensure:

- Equal spacing above "Clear board (esc)" and below "Download script ->"?
- The code-styled text ("https://github.com/..." and "chmod 701 ...") is the same size as the rest of the text around it? It's ok if this makes it wrap onto multiple lines.

After that, I'll merge right away. I appreciate the help!

**Comment by RamanaRaj7** [comment]
the reason I made the code-styled text smaller is because "https://github.com/..."  this was overflowing to the right since that  is in code-styled text I made "chmod 701 ..." also small to make them look uniform and anyways they can't run the command in they mobile so ig it won't be a problem and the overflow was noticed when I tried to run the site in a device connected to my local network

**Comment by RamanaRaj7** [comment]
Equal spacing above "Clear board (esc)" and below "Download script ->" done and if given some more spacing above and below it might look a little odd on desktop view ig.

**Comment by mattrltrent** [comment]
Merged!

**Pull request merged**
